import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import MarqueText from "./components/Navbar/MarqueText";
import Footer from "./components/Footer/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Bangla News ",
  description: "Generated by rakibhossendev",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col mt-3">
        
        <Navbar/>
        <MarqueText/>
        <div className="bg-[#FAFAFA]">

        {children}
        <Footer/>
        </div>
        
        </body>
    </html>
  );
}
