import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import MarqueText from "./components/Navbar/MarqueText";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <MarqueText/>
        <div className="bg-[#FAFAFA]">

        {children}
        </div>
   
        </body>
    </html>
  );
}
